/**
 * Created by adnanbasar on 20/05/2017.
 *
 * @flow
 */

import LocaleManager from './LocaleManager'

const strings = {
    en: {
        appName: 'Sebet.im',
        account: 'My Account',
        add: 'Add',
        address: 'Address',
        addressFound: 'Address Found',
        addressNotEmpty: 'Address cannot be empty.',
        back: 'Back',
        cancel: 'Cancel',
        cancelOrderTitle: 'Cancel This Order?',
        cart: 'Cart',
        checkout: 'Checkout',
        clearCartMessage: 'Do you want to remove all items from cart?',
        clearCartTitle: 'Clear items from cart.',
        currency: 'TMT',
        editAddress: 'Edit Address',
        english: 'English',
        express: 'Express',
        expressMessage: 'EXPRESS: Within 35 minutes',
        home: 'Home',
        itemAdded: 'Item is added to Cart',
        items: 'Items',
        itemRemoved: 'Item is removed from cart.',
        localeChoose: 'Choose your language:',
        localeUpdate: 'Language will change after restart.',
        locationNeeded: 'Sebetim needs your location for delivery!',
        login: 'Login',
        loginUppercase: 'LOGIN',
        logout: 'Logout',
        name: 'Name',
        nameNotEmpty: 'Name cannot be empty.',
        newProfile: 'New profile is saved. Thanks.',
        no: 'No',
        notifications: 'Notifications',
        orderCanceled: 'Order has been canceled.',
        orderGiven: 'Order is given and waiting for approval.',
        orderState: {
            nonApproved: 'Not Approved',
            approved: 'Approved - On Road',
            delivered: 'Delivered',
            canceled: 'Canceled'
        },
        password: 'Password',
        password6Characters: 'Password must be at least 6 characters.',
        phone: 'Phone',
        phonePasswordWrong: 'Phone or Password is wrong!',
        phone8Characters: 'Phone cannot be empty or less than 8 digits.',
        register: 'Register',
        remove: 'Remove',
        russian: 'Russian',
        save: 'Save',
        search: 'Search',
        signup: 'Sign Up',
        signupUppercase: 'SIGN UP',
        shopCategory: 'Shop By Category',
        shopOffers: 'Shop By Offers',
        standard: 'Standard',
        standardMessage: 'STANDART: Within 2 hours',
        turkmen: 'Turkmen',
        unknown: 'Unknown',
        useThis: 'Use This',
        useLocation: 'USE THIS LOCATION',
        usernameExits: 'This phone is already registered!',
        yes: 'Yes',
        welcome: 'Welcome',
        welcomeSlogan: 'Turkmenistan\'s Online Supermarket'
    },
    tm: {
        appName: 'Sebet.im',
        account: 'Hasabym',
        add: 'Goş',
        address: 'Adres',
        addressFound: 'Adres Tapylmady',
        addressNotEmpty: 'Adresi boş goýmaň.',
        back: 'Back',
        cancel: 'Bes et',
        cancelOrderTitle: 'Bu sargyt yza gaýtarylsynmy?',
        cart: 'Sebet',
        checkout: 'Töleg',
        clearCartMessage: 'Sebetdäki ähli harytlary çykarmak isleýäňizmi?',
        clearCartTitle: 'Sebetdäki harytlary çykar.',
        currency: 'TMT',
        editAddress: 'Edit Address',
        english: 'Iňlisçe',
        express: 'Çalt',
        expressMessage: 'TIZ WAGTDA: 35 minudyň dowamynda',
        home: 'Baş Sahypa',
        itemAdded: 'Haryt sebete goşuldy.',
        items: 'Haryt',
        itemRemoved: 'Haryt sebetden çykaryldy.',
        localeChoose: 'Dil Saýlaň:',
        localeUpdate: 'Programma täzeden açylandan soň dili üýtgär.',
        locationNeeded: 'Haryt tabşyrygy üçin salgyňyz gerek.',
        login: 'Giriş',
        loginUppercase: 'GIRIŞ',
        logout: 'Çykyş',
        name: 'Adyňyz',
        nameNotEmpty: 'Adyňyzy boş goýmaň.',
        newProfile: 'Täze agzalyk döredildi. Minnetdar.',
        no: 'Ýok',
        notifications: 'Bildirişler',
        orderCanceled: 'Sargyt yzyna gaýtaryldy.',
        orderGiven: 'Sargydyňyz kabul edildi we tassyklanmagyna garaşylýar.',
        orderState: {
            nonApproved: 'Tassyklanmady',
            approved: 'Tassyklandy - Ýolda',
            delivered: 'Tabşyryldy',
            canceled: 'Yzyna Gaýtaryldy'
        },
        password: 'Açar Sözi',
        password6Characters: 'Açar sözi azyndan 6 harp bolmaly.',
        phone: 'Telefon Belgiňiz',
        phonePasswordWrong: 'Telefon belgiňiz ýa-da açar sözüňiz ýalňyş!',
        phone8Characters: 'Telefon belgiňizi boş goýmaň.',
        register: 'Agza Bol',
        remove: 'Poz',
        russian: 'Rusça',
        save: 'Ýatda Sakla',
        search: 'Gözle',
        signup: 'Agza Bol',
        signupUppercase: 'AGZA BOL',
        shopCategory: 'Kategoriýa Boýunça Söwda',
        shopOffers: 'Teklip Boýunça Söwda',
        standard: 'Standart',
        standardMessage: 'STANDART: 2 sagadyň dowamynda',
        turkmen: 'Türkmençe',
        unknown: 'Belli däl',
        useThis: 'Şuny Ulan',
        useLocation: 'USE THIS LOCATION',
        usernameExits: 'Bu telefon belgisi öň registrasiýa edilen!',
        yes: 'Hawa',
        welcome: 'Hoş Geldiňiz',
        welcomeSlogan: 'Türkmenistanyň E-Söwdasy'
    },
    ru: {
        appName: 'Sebet.im',
        account: 'Мой Aккаунт',
        add: 'Добавить',
        address: 'Адрес Доставки',
        addressFound: 'Адрес Hайден',
        addressNotEmpty: 'Адрес не может быть пуст.',
        back: 'Back',
        cancel: 'Отменить',
        cancelOrderTitle: 'Отменить этот заказ?',
        cart: 'Корзина',
        checkout: 'Оплата',
        clearCartMessage: 'Сбросить все товари из корзины?',
        clearCartTitle: 'Сбросить товары из корзины.',
        currency: 'TMT',
        editAddress: 'Edit Address',
        english: 'Английский',
        express: 'Експресс Доставка',
        expressMessage: 'ЕКСПРЕСС: В течении 35 минут',
        home: 'Главная',
        itemAdded: 'Товары добавлены в кoрзину.',
        items: 'Товары',
        itemRemoved: 'Товары удалены из корзины.',
        localeChoose: 'Выбрать язык:',
        localeUpdate: 'Язык изменится после перезагрузки.',
        locationNeeded: 'Себетим нужен ваше место положения для доставки!',
        login: 'Вход',
        loginUppercase: 'ВXOД',
        logout: 'Выход',
        name: 'Имя',
        nameNotEmpty: 'Имя не может быть пуст.',
        newProfile: 'Новая профиль сохранена. Спасибо.',
        no: 'Hет',
        notifications: 'Увeдомления',
        orderCanceled: 'Заказ отменено.',
        orderGiven: 'Заказ принят и ждет потверждения.',
        orderState: {
            nonApproved: 'Не Yтверждено',
            approved: 'Утверждено - В Пути',
            delivered: 'Доставлено',
            canceled: 'Отменено'
        },
        password: 'Пароль',
        password6Characters: 'Пароль должен быть не менее 6 символов.',
        phone: 'Телефон',
        phonePasswordWrong: 'Ошибка при ввидении номера или пароля.',
        phone8Characters: 'Номер телефона не может быть пуст или менее 8 цифров.',
        register: 'Регистрация',
        remove: 'Сбросить',
        russian: 'Русский',
        save: 'Сохранить',
        search: 'Поиск',
        signup: 'Зарегистрироваться',
        signupUppercase: 'ЗАРЕГИСТРИРОВАТЬСЯ',
        shopCategory: 'Заказ По Kатегориям',
        shopOffers: 'Заказ По Популярности',
        standard: 'Стандартная Доставка',
        standardMessage: 'СТАНДАРТ: В течении 2-x часов',
        turkmen: 'Туркменский Язык',
        unknown: 'Неизвестный.',
        useThis: 'Используйте это.',
        useLocation: 'USE THIS LOCATION',
        usernameExits: 'Этот номер уже зарегистрирован!',
        yes: 'Да',
        welcome: 'Добро Пожаловать',
        welcomeSlogan: 'Oнлайн Pынок Туркменистана'
    }
}

export default strings[LocaleManager.locale]