/**
 * Created by adnanbasar on 20/05/2017.
 *
 * @flow
 */

import LocaleManager from './LocaleManager'

const strings = {
    en: {
        appName: 'Sebetim',
        account: 'My Account',
        add: 'Add',
        address: 'Address',
        cancel: 'Cancel',
        cart: 'Cart',
        checkout: 'Checkout',
        clearCartMessage: 'Do you want to remove all items from cart?',
        clearCartTitle: 'Clear Items from Cart',
        currency: 'TMT',
        english: 'English',
        express: 'Express',
        expressMessage: 'EXPRESS: By Tomorrow 8:30 AM',
        home: 'Home',
        itemAdded: 'Item is added to Cart',
        items: 'Items',
        itemRemoved: 'Item is removed from Cart',
        localeChoose: 'Choose your language:',
        localeUpdate: 'Language will change after restart',
        login: 'Login',
        logout: 'Logout',
        name: 'Name',
        notifications: 'Notifications',
        orderGiven: 'Order is given and waiting for approval',
        password: 'Password',
        password6Characters: 'Password must be at least 6 characters',
        phone: 'Phone',
        phonePasswordWrong: 'Phone or Password is wrong!',
        register: 'Register',
        remove: 'Remove',
        russian: 'Russian',
        save: 'Save',
        search: 'Search',
        shopCategory: 'Shop By Category',
        shopOffers: 'Shop By Offers',
        standard: 'Standard',
        standardMessage: 'STANDART: Tomorrow 5:00 PM to 19:30 PM',
        turkmen: 'Turkmence',
        unknown: 'Unknown',
        usernameExits: 'This phone is already registered!',
        welcome: 'Welcome'
    },
    tm: {
        appName: 'Sebetim',
        account: 'Hasabym',
        add: 'Goş',
        address: 'Adres',
        cancel: 'Bes et',
        cart: 'Sebet',
        checkout: 'Töleg',
        clearCartMessage: 'Sebetdäki ähli harytlary çykarmak isleýänizmi?',
        clearCartTitle: 'Sebetdäki harytlary çykar',
        currency: 'TMT',
        english: 'Iňlisçe',
        express: 'Çalt',
        expressMessage: 'ÇALT: Ertir sagat 8:30-a çenli',
        home: 'Baş Sahypa',
        itemAdded: 'Haryt sebete goşuldy',
        items: 'Haryt',
        itemRemoved: 'Haryt sebetden çykaryldy',
        localeChoose: 'Dil Saýlaň:',
        localeUpdate: 'Programma tazeden açylandan soň dili üýtgär',
        login: 'Giriş',
        logout: 'Çykyş',
        name: 'Adyňyz',
        notifications: 'Bildirişler',
        orderGiven: 'Sargydyňyz kabul edildi we tassyklanmagyna garaşylýar',
        password: 'Açar Sözi',
        password6Characters: 'Açar sözi azyndan 6 harp bolmaly',
        phone: 'Telefon Belgiňiz',
        phonePasswordWrong: 'Telefon belgiňiz ýa-da açar sözüňiz ýalňyş!',
        register: 'Agza Bol',
        remove: 'Poz',
        russian: 'Rusça',
        save: 'Ýatda Sakla',
        search: 'Gözle',
        shopCategory: 'Kategoriýa Boýunça Söwda',
        shopOffers: 'Teklip Boýunça Söwda',
        standard: 'Standart',
        standardMessage: 'STANDART: Ertir sagat 17:00-19:30 aralygy',
        turkmen: 'Türkmençe',
        unknown: 'Belli däl',
        usernameExits: 'Bu telefon belgisi öň registrasiýa edilen!',
        welcome: 'Hoş Geldiňiz'
    },
    ru: {
        appName: 'Sebetim',
        account: 'My Account',
        add: 'Add',
        address: 'Address',
        cancel: 'Cancel',
        cart: 'Cart',
        checkout: 'Checkout',
        clearCartMessage: 'Do you want to remove all items from cart?',
        clearCartTitle: 'Clear Items from Cart',
        currency: 'TMT',
        english: 'English',
        express: 'Express',
        expressMessage: 'EXPRESS: By Tomorrow 8:30 AM',
        home: 'Home',
        itemAdded: 'Item is added to Cart',
        items: 'Items',
        itemRemoved: 'Item is removed from Cart',
        localeChoose: 'Choose your language:',
        localeUpdate: 'Language will change after restart',
        login: 'Login',
        logout: 'Logout',
        name: 'Name',
        notifications: 'Notifications',
        orderGiven: 'Order is given and waiting for approval',
        password: 'Password',
        password6Characters: 'Password must be at least 6 characters',
        phone: 'Phone',
        phonePasswordWrong: 'Phone or Password is wrong!',
        register: 'Register',
        remove: 'Remove',
        russian: 'Russian',
        save: 'Save',
        search: 'Search',
        shopCategory: 'Shop By Category',
        shopOffers: 'Shop By Offers',
        standard: 'Standard',
        standardMessage: 'STANDART: Tomorrow 5:00 PM to 19:30 PM',
        turkmen: 'Turkmence',
        unknown: 'Unknown',
        usernameExits: 'This phone is already registered!',
        welcome: 'Welcome'
    }
}

export default strings[LocaleManager.locale]